linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign

run:
  timeout: 5m
  go: "1.21"

issues:
  max-same-issues: 0
  exclude-use-default: false
